# Generated by Django 3.1.7 on 2021-03-13 18:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cmdfoodapi', '0002_location'),
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('product_id', models.IntegerField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100)),
                ('price', models.IntegerField()),
                ('image_url', models.ImageField(blank=True, upload_to='products/', verbose_name='Product Image')),
                ('aisle_number', models.IntegerField()),
                ('aisle_side', models.CharField(max_length=2)),
                ('aisle_bay', models.CharField(max_length=10)),
                ('picked_up', models.BooleanField()),
            ],
        ),
    ]
