# Generated by Django 3.1.7 on 2021-03-13 19:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cmdfoodapi', '0003_product'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProductList',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('completed', models.BooleanField()),
                ('location', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='productlists', related_query_name='productlist', to='cmdfoodapi.location')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='productlists', related_query_name='productlist', to='cmdfoodapi.product')),
                ('shopper', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='productlists', related_query_name='productlist', to='cmdfoodapi.shopper')),
            ],
        ),
    ]
